// Generates type-safe Dart file with const asset references

import 'dart:io';
import 'package:dart_style/dart_style.dart';
import 'package:mason_logger/mason_logger.dart';

import '../models/config.dart';
import 'asset_scanner.dart';
import 'naming_converter.dart';

class CodeGenerator {
  final Directory projectRoot;
  final GenerateConfig config;
  final Logger? logger;

  CodeGenerator({
    required this.projectRoot,
    GenerateConfig? config,
    this.logger,
  }) : config = config ?? GenerateConfig();

  Future<void> generate() async {
    final scanner = AssetScanner(projectRoot: projectRoot);
    final assets = await scanner.scan();

    if (assets.isEmpty) {
      logger?.warn('⚠️  No assets found.');
      return;
    }

    final code = _generateCode(assets);

    final formatter = DartFormatter();
    final formatted = formatter.format(code);

    final outputFile = File('${projectRoot.path}/${config.output}');
    await outputFile.parent.create(recursive: true);
    await outputFile.writeAsString(formatted);

    logger?.info(
      '✅ Generated ${config.output} (${assets.length} assets)',
    );
  }

  Future<bool> isUpToDate() async {
    final outputFile = File('${projectRoot.path}/${config.output}');

    if (!outputFile.existsSync()) return false;

    final scanner = AssetScanner(projectRoot: projectRoot);
    final assets = await scanner.scan();
    final freshCode = _generateCodeWithoutTimestamp(assets);

    final existingCode = await outputFile.readAsString();
    // Compare ignoring the timestamp line
    final existingWithoutTimestamp = existingCode.replaceFirst(
      RegExp(r'// Generated by dart_assets on .*\n'),
      '',
    );
    final freshWithoutTimestamp = freshCode.replaceFirst(
      RegExp(r'// Generated by dart_assets on .*\n'),
      '',
    );

    return existingWithoutTimestamp.trim() == freshWithoutTimestamp.trim();
  }

  String _generateCode(List<ScannedAsset> assets) {
    final buffer = StringBuffer();

    buffer.writeln('// GENERATED CODE - DO NOT MODIFY BY HAND');
    buffer.writeln('// Generated by dart_assets on ${DateTime.now()}');
    buffer.writeln();
    buffer.writeln('// ignore_for_file: constant_identifier_names');
    buffer.writeln('// ignore_for_file: non_constant_identifier_names');
    buffer.writeln();

    buffer.writeln('/// Auto-generated asset references.');
    buffer.writeln('class ${config.className} {');
    buffer.writeln('  ${config.className}._();');
    buffer.writeln();

    final usedNames = <String>{};
    for (final asset in assets) {
      final name = NamingConverter.toUniqueIdentifier(asset.name, usedNames);
      usedNames.add(name);
      buffer.writeln("  static const String $name = '${asset.relativePath}';");
    }

    buffer.writeln();
    buffer.writeln('  /// All asset paths.');
    buffer.writeln('  static const List<String> all = [');
    final usedNames2 = <String>{};
    for (final asset in assets) {
      final name = NamingConverter.toUniqueIdentifier(asset.name, usedNames2);
      usedNames2.add(name);
      buffer.writeln('    $name,');
    }
    buffer.writeln('  ];');
    buffer.writeln('}');

    return buffer.toString();
  }

  String _generateCodeWithoutTimestamp(List<ScannedAsset> assets) {
    return _generateCode(assets);
  }
}
